name: Pruebas unitarias Release
on:
  push:
    branches: [develop]
permissions:
  contents: write
  pull-requests: write
jobs:
  job1:
    name: Nombre_commit
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.commit_message.outputs.COMMIT_MSG}}
      salida_branch: ${{ steps.branch.outputs.branch}}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v4
    - name: Get last commit message
      id: commit_message
      run: |
        echo "COMMIT_MSG=${{ github.event.head_commit.message }}">> $GITHUB_OUTPUT
    - name: Get branch
      id: branch
      run: |
        echo "branch=${{ github.ref_name }}">> $GITHUB_OUTPUT
    - name: Print variable
      run: echo "${{ steps.commit_message.outputs.COMMIT_MSG}}"
    - name: Printbranch
      run: echo "${{ steps.branch.outputs.branch}}"
